[package]
name = "drone-openocd"
version = "0.15.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2021"
links = "libopenocd"
repository = "https://github.com/drone-os/drone"
homepage = "https://www.drone-os.com/"
documentation = "https://api.drone-os.com/drone-core/0.15/drone_openocd/"
license = "MIT OR Apache-2.0"
description = """
OpenOCD bindings for Drone, an Embedded Operating System.
"""

[build-dependencies]
bindgen = "0.60"
