edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
hex_literal_case = "Upper"
imports_granularity = "Module"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
version = "Two"
wrap_comments = true
